language: php

matrix:
    include:
        # Test with default configuration
        - { php: 7.1 }
        # Test against librabbitmq cutting-edge
        - { php: 7.1, env: LIBRABBITMQ_VERSION=master }
        # Test with lowest dependencies
        - { php: 7.1, env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' }

services: [rabbitmq]

before_script:
  - sh -c 'if [ "$LIBRABBITMQ_VERSION" != "" ]; then ./tests/bin/install_librabbitmq.sh; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi;'
  - composer selfupdate
  - composer update --prefer-source -n $COMPOSER_FLAGS
  - sh -c "sudo ./tests/bin/prepare_rabbit.sh"

script: vendor/bin/phpunit
